DjangoChatApplication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace="core")),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('create/<str:room_name>/', views.room, name='room'),
    path('create/connect/login', views.forward, name='room'),
    path('logout', views.logoutPage, name="logout"),
    path('', views.homePage, name="home"), 
    path('login/', views.loginPage, name="login"),
    path('register', views.registerPage, name="register"), 
]

core/models.py
from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.

User = get_user_model()

class Message(models.Model):
    author = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}".format(self.pk) 

class Chat(models.Model):
    participants = models.ManyToManyField(User, related_name='chats')
    messages = models.ManyToManyField(Message, blank=True)

    def __str__(self):
        return "{}".format(self.pk) 

    def get_roomname(username, friend):
        def get_userList(user):
            chats = Chat.objects.filter(participants=user.id)
            lst_user = []
            for chat in chats:
                lst_user.append(chat.id)
            return lst_user

        user_1 = User.objects.filter(username=username)[0]
        lst_user_1 = get_userList(user_1)

        user_2 = User.objects.filter(username=friend)[0]
        lst_user_2 = get_userList(user_2)
        
        res = list(set(lst_user_1).intersection(lst_user_2))
        if len(res) != 0:
            return res
        else:
            new_chat = Chat.objects.create()
            new_chat.participants.add(user_1)
            new_chat.participants.add(user_2)
            new_chat.save()
            return [new_chat.id]
    
    def get_friendname(roomname, username):
        chat = Chat.objects.filter(id=roomname)[0] 

        participants = chat.participants.all()
        user1 = participants[0].username

        if user1 != username:
            return user1
        else:
            return participants[1].username

    def last_10_messages(roomname):
        chat = Chat.objects.filter(id=roomname)[0]
        return chat.messages.order_by('-timestamp').all()[:10]

core/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.utils import timezone
from django.utils.safestring import mark_safe
import json


def registerPage(request):
    if request.user.is_authenticated:
        return redirect("/")
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user + '. Login to continue' )
                return redirect("/")
            else:
                messages.info(request, 'Please fill the details properly')

        context = {'form': form}
        return render(request, 'core/register.html', context)
    

def loginPage(request):
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                print('|| incorrect login credentials')
                messages.info(request, 'Username OR password is incorrect')


        context = {}
        return render(request, 'core/login.html', context)


def logoutPage(request):
    logout(request)
    print('|| user logged out')
    return redirect('login/')


@login_required(login_url="login/")
def homePage(request):
    return redirect('create/connect/')


def get_current_users():
    active_sessions = Session.objects.filter(expire_date__gte=timezone.now())
    user_id_list = []
    for session in active_sessions:
        data = session.get_decoded()
        user_id_list.append(data.get('_auth_user_id', None))
    # Query all logged in users based on id list
    return User.objects.filter(id__in=user_id_list)


@login_required(login_url="login/")
def room(request, room_name):
    current_users = get_current_users()
    return render(request, 'core/chat.html', {
        'room_name': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
        # 'current_users': mark_safe(json.dumps(current_users))
        'current_users': current_users
    })


def forward(request):
    return redirect("login/")

templates/core/chat.html
<!DOCTYPE html>
{% load static %}
{% load strip_double_quotes %}

<html lang="en">
    <head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
</head>
<body>

<div class="messaging">
  <div class="inbox_msg">
	<div class="inbox_people">
	  <div class="headind_srch">
		<div class="recent_heading">
		  <h4>User: {{ username|strip_double_quotes }}</h4>
        </div>
        <div class="recent_heading" style="float:right; width: auto;">
            <h4><a href="{% url 'core:logout' %}">Logout</a></h4>
          </div>
	  </div>
	  <div class="inbox_chat scroll">
        {% for user in current_users %}	
            {% if user.username is not username %}
                <div class="chat_list" onclick="getuser(this);" style="cursor: pointer;" data-username={{user.username}}>
                <div class="chat_people">
                    <div class="chat_img"> <img src="https://ptetutorials.com/images/user-profile.png" alt="sunil"> </div>
                    <div class="chat_ib">
                    <h5 class="users">{{user.username}}</h5>
                    </div>
                </div>
                </div>
            {% endif %}
        {% endfor %}
	  </div>
	</div>
	<div class="mesgs">
	  <div class="msg_history" id="chat-log">
	  </div>
	  <div class="type_msg">
		<div class="input_msg_write">
		  <input type="text" id="chat-message-input" class="write_msg" placeholder="Type a message" />
		  <button class="msg_send_btn" id="chat-message-submit" type="button"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
		</div>
	  </div>
	</div>
  </div>
</div>
<script src="{% static 'js/reconnecting-websocket.js' %}"></script>
<script>
var roomName = {{ room_name }};
var userName = {{ username }};

// create new web socket
const chatSocket = new ReconnectingWebSocket(
    'ws://'
    + window.location.host
    + '/ws/create/'
    + roomName
    + '/'
);

function deleteUser(){
    var users = document.getElementsByClassName("chat_list")
    for (i=0; i<users.length; i++) {
        if (users[i].getAttribute("data-username") === userName){
            users[i].remove();
            break;
        }
    }
}

function getuser(e) {
    // e.classList.add("active_chat");
    friend = e.firstElementChild.lastElementChild.firstElementChild.innerText
    chatSocket.send(JSON.stringify({
		'command': 'get_roomname',
		'user': userName,
		'friend': friend
	}));
}

chatSocket.onopen = function(e) {
    deleteUser();
    fetchMessages();
    if (roomName !== "connect") {
        chatSocket.send(JSON.stringify({
            'command': 'get_friendname',
            'roomname': roomName,
            'username': userName
        }));
    }
}

// On receiving a message, adding it to html
chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);	
	if (data['command'] === 'fetch_message') {
		for (let i=data['messages'].length-1; i>=0; i--){
			createMessage(data['messages'][i]);
		}
	} else if (data['command'] === 'new_message'){
		createMessage(data['message']);
	} else if (data['command'] === 'get_roomname'){
		window.location.pathname = '/create/' + data['roomname'] + '/';
    } 
    else if (data['command'] === 'get_friendname'){
        user_active(data["friendname"]);
	} 
};


// On closing the web socket
chatSocket.onclose = function (e) {
    console.error('Chat socket closed unexpectedly');
};

// When clicking the enter key 
document.querySelector('#chat-message-input').onkeyup = function (e) {
	if (e.keyCode === 13) {  // enter, return
        document.querySelector('#chat-message-submit').click();
    }
};

// Sending the chat message
document.querySelector('#chat-message-submit').onclick = function (e) {
    const messageInputDom = document.querySelector('#chat-message-input');
    const message = messageInputDom.value;
    chatSocket.send(JSON.stringify({
        'command': 'new_message',
        'message': message,
		'from': userName,
		'roomname': roomName
    }));
    messageInputDom.value = '';
};

// fetch last 10 messages
function fetchMessages() {
	chatSocket.send(JSON.stringify({
		'command': 'fetch_messages',
		'roomname': roomName
	}));
}

// create new message in html
function createMessage(data) {
	var author = data['author'];

    var div1 = document.createElement('div');
    var div2 = document.createElement('div');

    var pTag = document.createElement('p');
    pTag.textContent = data.content;
    
    if (author === userName) {
        div1.className = 'outgoing_msg';
        div2.className = 'sent_msg';
        div2.appendChild(pTag);
        div1.appendChild(div2);
    } else {
        var div3 = document.createElement('div');

        var imgDiv = document.createElement('div');
        imgDiv.className = "incoming_msg_img";
        var imgTag = document.createElement('img');
        imgTag.src = 'https://ptetutorials.com/images/user-profile.png';
        imgDiv.appendChild(imgTag);

        div1.className = 'incoming_msg';
        div2.className = 'received_msg';
        div2.appendChild(div3);

        div3.className = 'received_withd_msg';
        div3.appendChild(pTag);
        div2.appendChild(div3);
        div1.appendChild(imgDiv);
        div1.appendChild(div2);
    }    
    document.querySelector('#chat-log').appendChild(div1);
}

function user_active(friendname) {
    var users = document.getElementsByClassName("users");
    for (i=0; i<users.length; i++) {
        if (users[i].innerText === friendname){
            users[i].parentElement.parentElement.parentElement.classList.add("active_chat");
        }
    }
}

</script>
</body>
</html>

templates/core/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>

<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="{% url 'core:login' %}" class="active" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="{% url 'core:register' %}" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" method="post" role="form" style="display: block;">
                                    {% csrf_token %}
                                    <div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<!-- <div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div> -->
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
											</div>
										</div>
									</div>
									<!-- <div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="https://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div>
									</div> -->
                                </form>
                                {% for message in messages %}
                                    <p>{{message}}</p>
                                {% endfor %}
								<!-- <form id="register-form" action="https://phpoll.com/register/process" method="post" role="form" style="display: none;">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
								</form> -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
<!-- <!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action="">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username...">
        <input type="password" name="password" placeholder="Password...">
        <input type="submit" name="Login">
    </form>


    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
</body>
</html> -->

templates/core/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>

<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-6">
								<a href="{% url 'core:login' %}" id="login-form-link">Login</a>
							</div>
							<div class="col-xs-6">
								<a href="{% url 'core:register' %}" class="active" id="register-form-link">Register</a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="register-form" method="post" role="form">
                                    {% csrf_token %}
                                    <div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
									</div>
									<div class="form-group">
										<input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Email Address" value="">
									</div>
									<div class="form-group">
										<input type="password" name="password1" id="password" tabindex="2" class="form-control" placeholder="Password">
									</div>
									<div class="form-group">
										<input type="password" name="password2" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
											</div>
										</div>
									</div>
                                </form>
                                {% for message in messages %}
                                    <p>{{message}}</p>
                                {% endfor %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>